### ISSUE TITLE
Create a test route that the frontend can hit to test that express and React are communicating properly. 

### ISSUE THREAD

**Issue by SilasCundiff** [SilasCundiff/NorthArk#31]
(tip: may need to add cors).

**Comment by HaoHuynh0301** [comment]
Hi. I think I can solve this issue. Can you assign me for this ? Thank you ! @SilasCundiff

**Comment by SilasCundiff** [comment]
Hey @HaoHuynh0301, Thanks for your interest in our project, but this is an in house group project for Minos Labs. It's meant to be a chance for people in our capstone group to learn and show what they know, so we aren't currently accepting any outside commits. Sorry!
